apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: grocery-store
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 3000       # Service port
      targetPort: 3000 # Container port
      nodePort: 32301  # NodePort (same as your previous random port)
      protocol: TCP
  selector:
    app: frontend
